In [1]:
words = open('names.txt', 'r').read().splitlines()

In [2]:
words[:5]

['emma', 'olivia', 'ava', 'isabella', 'sophia']

In [3]:
chars = sorted(list(set(''.join(words))))
chars

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [4]:
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
stoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [5]:
itos = {i:s for s, i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [6]:
import torch 

N = torch.zeros(27, 27, 27)

In [7]:
for w in words[:3]:
    w = '.' + '.' + w + '.' + '.'
    for ch1, ch2, ch3 in zip(w, w[1:], w[2:]):
        print(ch1, ch2, ch3)


. . e
. e m
e m m
m m a
m a .
a . .
. . o
. o l
o l i
l i v
i v i
v i a
i a .
a . .
. . a
. a v
a v a
v a .
a . .


In [8]:
for w in words:
    w = '.' + '.' + w + '.' + '.'
    for ch1, ch2, ch3 in zip(w, w[1:], w[2:]):
        ix1, ix2, ix3 = stoi[ch1], stoi[ch2], stoi[ch3]
        N[ix1, ix2, ix3] += 1
N

tensor([[[0.0000e+00, 4.4100e+03, 1.3060e+03,  ..., 1.3400e+02,
          5.3500e+02, 9.2900e+02],
         [0.0000e+00, 2.0700e+02, 1.9000e+02,  ..., 2.7000e+01,
          1.7300e+02, 1.5200e+02],
         [0.0000e+00, 1.6900e+02, 0.0000e+00,  ..., 0.0000e+00,
          4.0000e+00, 0.0000e+00],
         ...,
         [0.0000e+00, 5.7000e+01, 0.0000e+00,  ..., 1.0000e+00,
          1.7000e+01, 1.1000e+01],
         [0.0000e+00, 2.4600e+02, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 2.0000e+00],
         [0.0000e+00, 4.5600e+02, 0.0000e+00,  ..., 0.0000e+00,
          9.1000e+01, 1.0000e+00]],

        [[6.6400e+03, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [4.0000e+01, 0.0000e+00, 5.0000e+00,  ..., 0.0000e+00,
          2.0000e+01, 1.1000e+01],
         [3.6000e+01, 2.8000e+01, 2.0000e+01,  ..., 0.0000e+00,
          1.2000e+01, 0.0000e+00],
         ...,
         [1.1000e+01, 5.0000e+00, 0.0000e+00,  ..., 1.7000e+01,
          6.000

In [9]:
# 27, 27, 27
# 27, 27,  1

P = (N+1).float()
P = P / P.sum(2, keepdim=True) 
P.shape

torch.Size([27, 27, 27])

In [10]:
res = ""
ix = (0, 0)
names = []

for i in range(50):
    while True:
        ix = torch.multinomial(P[ix], num_samples=1, replacement=True)
        curr_let = itos[ix.item()]
        res += curr_let

        if curr_let == '.':
            break

        if len(res) >= 2:
            ix = (stoi[res[len(res) - 2]], stoi[res[len(res)-1]])
        else:
            ix = (0, stoi[res])
    names.append(res)
    res = ""
    ix = (0, 0)
names




['mah.',
 'nalen.',
 'lean.',
 'kolah.',
 'endainox.',
 'brir.',
 'ubra.',
 'arein.',
 'daikariayceshiahiannel.',
 'wrlm.',
 'bene.',
 'danaaric.',
 'dree.',
 'abrygraniwxhfyamirger.',
 'incalayaah.',
 'lu.',
 'swaynne.',
 'aistatmlron.',
 'kenoris.',
 'llanyxeillan.',
 'taar.',
 'lie.',
 'leirisri.',
 'saazar.',
 'le.',
 'lenael.',
 'jahen.',
 'islen.',
 'tulmesha.',
 'jah.',
 'danice.',
 'jaelynn.',
 'akylanson.',
 'alynne.',
 'aoliahleigh.',
 'sayldee.',
 'tyleentouisoni.',
 'chuni.',
 'foghtk.',
 'coran.',
 'ail.',
 'cala.',
 'klivio.',
 'bri.',
 'ah.',
 'da.',
 'roumiymaleer.',
 'se.',
 'maricon.',
 'tary.']

In [11]:
log_likelihood = 0
n = 0
for w in words:
    w = '.' + '.' + w + '.' + '.'
    for ch1, ch2, ch3 in zip(w, w[1:], w[2:]):
        ix1, ix2, ix3 = stoi[ch1], stoi[ch2], stoi[ch3]
        prob = P[ix1, ix2, ix3]
        log_prob = torch.log(prob)
        log_likelihood += log_prob
        n += 1

nll = -log_likelihood
nll /= n
print(f"Loss: {nll.item(): .4f}") 

Loss:  1.9420


# Approach Two: Neural Net

In [15]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F

In [12]:
chars = sorted(list(set(''.join(words))))
itos = {i+1:s for i, s in enumerate(chars)}
itos[0] = "."
stoi = {s:i for i, s in itos.items()}

stoi


{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [13]:
def multi_hot(tuples, num_classes):
    multi_hot_matrix = torch.zeros((len(tuples), num_classes))

    for i, indices in enumerate(tuples):
        multi_hot_matrix[i, indices] = 1  

    return multi_hot_matrix

multi_hot([((1, 2), (3, 4))], num_classes=27)


tensor([[0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
xs, ys = [], [] # (., .) --> (e)
for w in words:
    w = "." + "." + w + "." + "."
    for ch1, ch2, ch3 in zip(w, w[1:], w[2:]):
        ix1, ix2, ix3 = stoi[ch1], stoi[ch2], stoi[ch3]
        xs.append((ix1, ix2))
        ys.append(ix3)
print(xs[:6])
print(ys[:6])
print([(x, y) for x, y in zip(xs[:2], ys[:2])])

[(0, 0), (0, 5), (5, 13), (13, 13), (13, 1), (1, 0)]
[5, 13, 13, 1, 0, 0]
[((0, 0), 5), ((0, 5), 13)]


In [21]:
x_enc = torch.tensor([])
for b1, b2 in xs:
    b1_tens = F.one_hot(torch.tensor(b1), num_classes=27)
    b2_tens = F.one_hot(torch.tensor(b2), num_classes=27)
    b1_b2_tens = torch.cat((b1_tens.unsqueeze(dim=0), b2_tens.unsqueeze(dim=0)), dim=1)
    x_enc = torch.cat((x_enc, b1_b2_tens), dim=0)


In [31]:
x_enc = x_enc.float()

In [32]:
x_enc.shape

torch.Size([260179, 54])

In [33]:
W = torch.randn((54, 54), requires_grad=True)

In [34]:
W

tensor([[-1.0527,  0.8903, -0.3166,  ...,  0.4945,  0.1503, -0.2230],
        [ 0.1197,  0.0655, -0.1010,  ..., -0.3716,  1.3543,  1.0434],
        [ 0.6108, -3.2354, -0.6814,  ..., -0.3057, -0.5844,  1.0226],
        ...,
        [-1.1673, -0.1527,  0.7677,  ...,  0.1921,  0.6206,  0.0663],
        [ 0.8398,  1.4980,  0.9162,  ...,  0.0911, -0.2679,  1.5232],
        [-2.3325, -1.0325,  0.2311,  ...,  0.8777,  0.9163,  1.8467]],
       requires_grad=True)

In [35]:
logits = x_enc @ W
counts = logits.exp()
probs = counts / counts.sum(1, keepdim=True)

In [36]:
probs[0].sum()

tensor(1.0000, grad_fn=<SumBackward0>)

In [37]:
# Initial Loss
loss = -probs[torch.arange(probs.shape[0]), ys].log().mean()
loss

tensor(4.8831, grad_fn=<NegBackward0>)

In [67]:
for i in range(101):
    # Forward Pass
    logits = x_enc @ W
    counts = logits.exp()
    probs = counts / counts.sum(1, keepdim=True)
    loss = -probs[torch.arange(probs.shape[0]), ys].log().mean()

    # Backwards Pass
    W.grad = None
    loss.backward()
    W.data += -10 * W.grad
    if i % 100 == 0:
        print(loss.item())

2.077633857727051
2.0741941928863525


In [ ]:
tens1 = F.one_hot(torch.tensor(0), num_classes=27).unsqueeze(0)
tens2 = F.one_hot(torch.tensor(3), num_classes=27).unsqueeze(0)
torch.cat((tens1, tens2), dim=1)

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0]])

In [68]:
# for i in range(10):
#     res = ""
#     ix = (0, 0)
#     while True:
#         ix1_tens= F.one_hot(torch.tensor(0), num_classes=27).unsqueeze(0)
#         ix2_tens = F.one_hot(torch.tensor(3), num_classes=27).unsqueeze(0)
#         xput = torch.cat((ix1_tens, ix2_tens), dim=1).float()
#         logits = xput @ W
#         counts = logits.exp()
#         probs = counts / counts.sum(1, keepdim=True)
#         ix = torch.multinomial(probs, num_samples=1, replacement=True)
#         if ix.item() >= 27:
#             ix = ix.item()-27
#             res += itos[ix]
#         else:
#             ix = ix.item()
#             res += itos[ix]

#         if ix == 0:
#             break 

#         if len(res) < 2:
#             ix = (0, ix)
#         else:
#             ix = (stoi[res[-1]], ix)

#     print(res)
