In [2]:
words = open('names.txt', 'r').read().splitlines()

In [3]:
words[:5]

['emma', 'olivia', 'ava', 'isabella', 'sophia']

In [4]:
chars = sorted(list(set(''.join(words))))
chars

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [5]:
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
stoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [6]:
itos = {i:s for s, i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [7]:
import torch 

N = torch.zeros(27, 27, 27)

In [8]:
for w in words[:3]:
    w = '.' + '.' + w + '.' + '.'
    for ch1, ch2, ch3 in zip(w, w[1:], w[2:]):
        print(ch1, ch2, ch3)


. . e
. e m
e m m
m m a
m a .
a . .
. . o
. o l
o l i
l i v
i v i
v i a
i a .
a . .
. . a
. a v
a v a
v a .
a . .


In [9]:
for w in words:
    w = '.' + '.' + w + '.' + '.'
    for ch1, ch2, ch3 in zip(w, w[1:], w[2:]):
        ix1, ix2, ix3 = stoi[ch1], stoi[ch2], stoi[ch3]
        N[ix1, ix2, ix3] += 1
N

tensor([[[0.0000e+00, 4.4100e+03, 1.3060e+03,  ..., 1.3400e+02,
          5.3500e+02, 9.2900e+02],
         [0.0000e+00, 2.0700e+02, 1.9000e+02,  ..., 2.7000e+01,
          1.7300e+02, 1.5200e+02],
         [0.0000e+00, 1.6900e+02, 0.0000e+00,  ..., 0.0000e+00,
          4.0000e+00, 0.0000e+00],
         ...,
         [0.0000e+00, 5.7000e+01, 0.0000e+00,  ..., 1.0000e+00,
          1.7000e+01, 1.1000e+01],
         [0.0000e+00, 2.4600e+02, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 2.0000e+00],
         [0.0000e+00, 4.5600e+02, 0.0000e+00,  ..., 0.0000e+00,
          9.1000e+01, 1.0000e+00]],

        [[6.6400e+03, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [4.0000e+01, 0.0000e+00, 5.0000e+00,  ..., 0.0000e+00,
          2.0000e+01, 1.1000e+01],
         [3.6000e+01, 2.8000e+01, 2.0000e+01,  ..., 0.0000e+00,
          1.2000e+01, 0.0000e+00],
         ...,
         [1.1000e+01, 5.0000e+00, 0.0000e+00,  ..., 1.7000e+01,
          6.000

In [10]:
# 27, 27, 27
# 27, 27,  1

P = (N+1).float()
P = P / P.sum(2, keepdim=True) 
P.shape

torch.Size([27, 27, 27])

In [11]:
res = ""
ix = (0, 0)
names = []

for i in range(50):
    while True:
        ix = torch.multinomial(P[ix], num_samples=1, replacement=True)
        curr_let = itos[ix.item()]
        res += curr_let

        if curr_let == '.':
            break

        if len(res) >= 2:
            ix = (stoi[res[len(res) - 2]], stoi[res[len(res)-1]])
        else:
            ix = (0, stoi[res])
    names.append(res)
    res = ""
    ix = (0, 0)
names




['arif.',
 'scily.',
 'maga.',
 'jamarie.',
 'tel.',
 'els.',
 'ri.',
 'jaeviloriyanyan.',
 'adena.',
 'mar.',
 'ce.',
 'drnwxmragk.',
 'than.',
 'dalerle.',
 'wile.',
 'cae.',
 'shike.',
 'zaleuadarmad.',
 'jean.',
 'cion.',
 'di.',
 'roberan.',
 'danoon.',
 'akata.',
 'asell.',
 'xaqustariahiellielyah.',
 'nia.',
 'kyrgellen.',
 'jer.',
 'keikeann.',
 'dalisan.',
 'hai.',
 'ter.',
 'veriusevieessiyahiyla.',
 'maceel.',
 'deleifd.',
 'tasa.',
 'aynneah.',
 'railaleyasta.',
 'ellershila.',
 'krlceylila.',
 'don.',
 'ka.',
 'carsh.',
 'mck.',
 'gilyldjaytthansimincen.',
 'la.',
 'beri.',
 'aman.',
 'treus.']

In [12]:
log_likelihood = 0
n = 0
for w in words:
    w = '.' + '.' + w + '.' + '.'
    for ch1, ch2, ch3 in zip(w, w[1:], w[2:]):
        ix1, ix2, ix3 = stoi[ch1], stoi[ch2], stoi[ch3]
        prob = P[ix1, ix2, ix3]
        log_prob = torch.log(prob)
        log_likelihood += log_prob
        n += 1

nll = -log_likelihood
nll /= n
print(f"Loss: {nll.item(): .4f}") 

Loss:  1.9420


# Approach Two: Neural Net

In [13]:
chars = sorted(list(set(''.join(words))))
itos = {i+1:s for i, s in enumerate(chars)}
itos[0] = "."
stoi = {s:i for i, s in itos.items()}

stoi


{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [101]:
def multi_hot(tuples, num_classes):
    multi_hot_matrix = torch.zeros((len(tuples), num_classes))

    for i, indices in enumerate(tuples):
        multi_hot_matrix[i, indices] = 1  

    return multi_hot_matrix

multi_hot([((1, 2), (3, 4))], num_classes=27)


tensor([[0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [88]:
xs, ys = [], [] # (., .) --> (e)
for w in words:
    w = "." + "." + w + "." + "."
    for ch1, ch2, ch3 in zip(w, w[1:], w[2:]):
        ix1, ix2, ix3 = stoi[ch1], stoi[ch2], stoi[ch3]
        xs.append((ix1, ix2))
        ys.append(ix3)
print(xs[:6])
print(ys[:6])
print([(x, y) for x, y in zip(xs[:2], ys[:2])])

[(0, 0), (0, 5), (5, 13), (13, 13), (13, 1), (1, 0)]
[5, 13, 13, 1, 0, 0]
[((0, 0), 5), ((0, 5), 13)]


In [89]:
xenc = multi_hot(xs, num_classes=27)

print(f"{xs[1]} --> {xenc[1]}")

(0, 5) --> tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [90]:
W = torch.randn((27, 27), requires_grad=True)

In [91]:
W

tensor([[ 7.6214e-01, -9.6164e-02,  4.0219e-02,  1.1764e+00,  3.1191e-01,
          2.3770e-02, -8.1651e-01,  8.4319e-01, -1.5790e+00,  2.0374e-01,
         -3.6681e-01,  1.5169e-01,  6.2586e-02,  7.4562e-01,  4.8838e-01,
          2.2197e-01,  5.7223e-01,  1.5885e-01, -4.4098e-01, -5.3759e-02,
         -7.5605e-01,  9.3506e-01,  7.0471e-01, -6.3101e-01, -2.9498e-03,
         -4.7219e-01,  1.0976e+00],
        [-6.6065e-01, -5.1478e-01,  1.6215e+00, -1.9661e+00,  5.3628e-01,
          4.9452e-01,  1.2195e-01,  6.9381e-01,  1.8171e+00,  1.1142e+00,
          1.5889e+00, -2.0620e+00,  1.3084e+00, -2.0276e+00, -6.0025e-01,
         -1.6648e+00, -8.0630e-01, -7.0448e-01,  1.3326e-01, -1.1041e+00,
          5.8051e-01,  2.4332e+00,  1.6750e+00, -1.2123e+00, -5.9868e-01,
         -2.1872e-01,  1.2624e-01],
        [ 9.8701e-01, -1.9508e-01, -1.5151e+00, -1.1740e+00,  1.6145e+00,
          6.9566e-01, -7.6680e-02, -1.3412e+00, -3.9570e+00, -4.9761e-01,
          8.9863e-01, -4.3497e-01, -8.00

In [92]:
logits = xenc @ W
counts = logits.exp()
probs = counts / counts.sum(1, keepdim=True)

In [93]:
probs[0].sum()

tensor(1., grad_fn=<SumBackward0>)

In [94]:
# Initial Loss
loss = -probs[torch.arange(probs.shape[0]), ys].log().mean()
loss

tensor(3.9619, grad_fn=<NegBackward0>)

In [99]:
for i in range(1000):
    # Forward Pass
    logits = xenc @ W
    counts = logits.exp()
    probs = counts / counts.sum(1, keepdim=True)
    loss = -probs[torch.arange(probs.shape[0]), ys].log().mean()

    # Backwards Pass
    W.grad = None
    loss.backward()
    W.data += -20 * W.grad
    print(loss.item())

2.376478433609009
2.3764662742614746
2.3764543533325195
2.3764421939849854
2.376429557800293
2.376417636871338
2.376405715942383
2.3763937950134277
2.3763816356658936
2.3763699531555176
2.3763582706451416
2.3763463497161865
2.3763346672058105
2.3763232231140137
2.3763110637664795
2.3762998580932617
2.3762879371643066
2.3762764930725098
2.376265287399292
2.376253604888916
2.3762426376342773
2.3762311935424805
2.3762199878692627
2.376208782196045
2.376197576522827
2.3761863708496094
2.3761754035949707
2.376164436340332
2.376152992248535
2.3761425018310547
2.376131534576416
2.3761205673217773
2.3761096000671387
2.376099109649658
2.3760881423950195
2.376077651977539
2.3760671615600586
2.37605619430542
2.3760457038879395
2.376035213470459
2.3760244846343994
2.376013994216919
2.3760037422180176
2.375993490219116
2.375983238220215
2.3759729862213135
2.375962495803833
2.3759522438049316
2.3759422302246094
2.375931978225708
2.3759219646453857
2.3759117126464844
2.375901699066162
2.3758919239044

In [119]:
for i in range(10):
    res = ""
    ix = (0, 0)
    while True:
        xput = multi_hot(ix, num_classes=27)
        logits = xput @ W
        counts = logits.exp()
        probs = counts / counts.sum(1, keepdim=True)
        ix = torch.multinomial(probs, num_samples=1, replacement=True)
        res += itos[ix[1].item()]

        if ix[1] == 0:
            break 

        if len(res) < 2:
            ix = (0, ix)
        else:
            ix = (stoi[res[-1]], ix)

    print(res)


li.
sa.
ka.
f.
hranoiyorqugai.
phi.
mayra.
fao.
ilege.
vae.
